CREATE TABLE IF NOT EXISTS APP_USER (
    ID BIGSERIAL PRIMARY KEY,
    USERNAME VARCHAR(100),
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(50)
);



CREATE TABLE IF NOT EXISTS DOCUMENT (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DOB DATE NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    FILE_NAME VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(1000),
    HASH VARCHAR(255),
    AGREE BOOLEAN DEFAULT FALSE,
    UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS resume_result (
    id BIGSERIAL PRIMARY KEY,
    candidate_id VARCHAR(255),
    name VARCHAR(255),
    score DOUBLE PRECISION,
    keyword_suggestions VARCHAR(2000),
    resume_path VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Clear existing users (safe to run multiple times)
DELETE FROM APP_USER;

-- Insert default admin user (using ON CONFLICT to handle re-runs)
INSERT INTO APP_USER (id, username, password, role) VALUES (
  1,
  '165468',
  '$2a$12$E7nT9DqIKi9UpKtWSJY.Oe2Q4a7f3ZYl5TI9WyeFBlGDwofAgs562',  -- ← admin123
  'ADMIN'
) ON CONFLICT (id) DO NOTHING;
